package com.bitshares.oases.chain

import bitshareskit.operations.OperationType
import com.bitshares.oases.R

val operationNameStringResMap: Map<OperationType, Int> = mapOf(
    OperationType.TRANSFER_OPERATION to R.string.operation_type_transfer,
    OperationType.LIMIT_ORDER_CREATE_OPERATION to R.string.operation_type_limit_order_create,
    OperationType.LIMIT_ORDER_CANCEL_OPERATION to R.string.operation_type_limit_order_cancel,
    OperationType.CALL_ORDER_UPDATE_OPERATION to R.string.operation_type_call_order_update,
    OperationType.FILL_ORDER_OPERATION to R.string.operation_type_fill_order,
    OperationType.ACCOUNT_CREATE_OPERATION to R.string.operation_type_account_create,
    OperationType.ACCOUNT_UPDATE_OPERATION to R.string.operation_type_account_update,
    OperationType.ACCOUNT_WHITELIST_OPERATION to R.string.operation_type_account_whitelist,
    OperationType.ACCOUNT_UPGRADE_OPERATION to R.string.operation_type_account_upgrade,
    OperationType.ACCOUNT_TRANSFER_OPERATION to R.string.operation_type_account_transfer,
    OperationType.ASSET_CREATE_OPERATION to R.string.operation_type_asset_create,
    OperationType.ASSET_UPDATE_OPERATION to R.string.operation_type_asset_update,
    OperationType.ASSET_UPDATE_BITASSET_OPERATION to R.string.operation_type_asset_update_bitasset,
    OperationType.ASSET_UPDATE_FEED_PRODUCERS_OPERATION to R.string.operation_type_asset_update_feed_producers,
    OperationType.ASSET_ISSUE_OPERATION to R.string.operation_type_asset_issue,
    OperationType.ASSET_RESERVE_OPERATION to R.string.operation_type_asset_reserve,
    OperationType.ASSET_FUND_FEE_POOL_OPERATION to R.string.operation_type_asset_fund_fee_pool,
    OperationType.ASSET_SETTLE_OPERATION to R.string.operation_type_asset_settle,
    OperationType.ASSET_GLOBAL_SETTLE_OPERATION to R.string.operation_type_asset_global_settle,
    OperationType.ASSET_PUBLISH_FEED_OPERATION to R.string.operation_type_asset_publish_feed,
    OperationType.WITNESS_CREATE_OPERATION to R.string.operation_type_witness_create,
    OperationType.WITNESS_UPDATE_OPERATION to R.string.operation_type_witness_update,
    OperationType.PROPOSAL_CREATE_OPERATION to R.string.operation_type_proposal_create,
    OperationType.PROPOSAL_UPDATE_OPERATION to R.string.operation_type_proposal_update,
    OperationType.PROPOSAL_DELETE_OPERATION to R.string.operation_type_proposal_delete,
    OperationType.WITHDRAW_PERMISSION_CREATE_OPERATION to R.string.operation_type_withdraw_permission_create,
    OperationType.WITHDRAW_PERMISSION_UPDATE_OPERATION to R.string.operation_type_withdraw_permission_update,
    OperationType.WITHDRAW_PERMISSION_CLAIM_OPERATION to R.string.operation_type_withdraw_permission_claim,
    OperationType.WITHDRAW_PERMISSION_DELETE_OPERATION to R.string.operation_type_withdraw_permission_delete,
    OperationType.COMMITTEE_MEMBER_CREATE_OPERATION to R.string.operation_type_committee_member_create,
    OperationType.COMMITTEE_MEMBER_UPDATE_OPERATION to R.string.operation_type_committee_member_update,
    OperationType.COMMITTEE_MEMBER_UPDATE_GLOBAL_PARAMETERS_OPERATION to R.string.operation_type_committee_member_update_global_parameters,
    OperationType.VESTING_BALANCE_CREATE_OPERATION to R.string.operation_type_vesting_balance_create,
    OperationType.VESTING_BALANCE_WITHDRAW_OPERATION to R.string.operation_type_vesting_balance_withdraw,
    OperationType.WORKER_CREATE_OPERATION to R.string.operation_type_worker_create,
    OperationType.CUSTOM_OPERATION to R.string.operation_type_custom,
    OperationType.ASSERT_OPERATION to R.string.operation_type_assert,
    OperationType.BALANCE_CLAIM_OPERATION to R.string.operation_type_balance_claim,
    OperationType.OVERRIDE_TRANSFER_OPERATION to R.string.operation_type_override_transfer,
    OperationType.TRANSFER_TO_BLIND_OPERATION to R.string.operation_type_transfer_to_blind,
    OperationType.BLIND_TRANSFER_OPERATION to R.string.operation_type_blind_transfer,
    OperationType.TRANSFER_FROM_BLIND_OPERATION to R.string.operation_type_transfer_from_blind,
    OperationType.ASSET_SETTLE_CANCEL_OPERATION to R.string.operation_type_asset_settle_cancel,
    OperationType.ASSET_CLAIM_FEES_OPERATION to R.string.operation_type_asset_claim_fees,
    OperationType.FBA_DISTRIBUTE_OPERATION to R.string.operation_type_fba_distribute,
    OperationType.BID_COLLATERAL_OPERATION to R.string.operation_type_bid_collateral,
    OperationType.EXECUTE_BID_OPERATION to R.string.operation_type_execute_bid,
    OperationType.ASSET_CLAIM_POOL_OPERATION to R.string.operation_type_asset_claim_pool,
    OperationType.ASSET_UPDATE_ISSUER_OPERATION to R.string.operation_type_asset_update_issuer,
    OperationType.HTLC_CREATE_OPERATION to R.string.operation_type_htlc_create,
    OperationType.HTLC_REDEEM_OPERATION to R.string.operation_type_htlc_redeem,
    OperationType.HTLC_REDEEMED_OPERATION to R.string.operation_type_htlc_redeemed,
    OperationType.HTLC_EXTEND_OPERATION to R.string.operation_type_htlc_extend,
    OperationType.HTLC_REFUND_OPERATION to R.string.operation_type_htlc_refund,
).withDefault { R.string.operation_type_unknown }
val operationDescriptionStringResMap: Map<OperationType, Int> = mapOf(
    OperationType.TRANSFER_OPERATION to R.string.operation_description_transfer,
//    OperationType.LIMIT_ORDER_CREATE_OPERATION to R.string.operation_description_limit_order_create,
    OperationType.LIMIT_ORDER_CANCEL_OPERATION to R.string.operation_description_limit_order_cancel,
    OperationType.CALL_ORDER_UPDATE_OPERATION to R.string.operation_description_call_order_update,
//    OperationType.FILL_ORDER_OPERATION to R.string.operation_description_fill_order,
    OperationType.ACCOUNT_CREATE_OPERATION to R.string.operation_description_account_create,
    OperationType.ACCOUNT_UPDATE_OPERATION to R.string.operation_description_account_update,
//    OperationType.ACCOUNT_WHITELIST_OPERATION to R.string.operation_description_account_whitelist,
//    OperationType.ACCOUNT_UPGRADE_OPERATION to R.string.operation_description_account_upgrade,
    OperationType.ACCOUNT_TRANSFER_OPERATION to R.string.operation_description_account_transfer,
    OperationType.ASSET_CREATE_OPERATION to R.string.operation_description_asset_create,
    OperationType.ASSET_UPDATE_OPERATION to R.string.operation_description_asset_update,
    OperationType.ASSET_UPDATE_BITASSET_OPERATION to R.string.operation_description_asset_update_bitasset,
    OperationType.ASSET_UPDATE_FEED_PRODUCERS_OPERATION to R.string.operation_description_asset_update_feed_producers,
    OperationType.ASSET_ISSUE_OPERATION to R.string.operation_description_asset_issue,
    OperationType.ASSET_RESERVE_OPERATION to R.string.operation_description_asset_reserve,
    OperationType.ASSET_FUND_FEE_POOL_OPERATION to R.string.operation_description_asset_fund_fee_pool,
    OperationType.ASSET_SETTLE_OPERATION to R.string.operation_description_asset_settle,
    OperationType.ASSET_GLOBAL_SETTLE_OPERATION to R.string.operation_description_asset_global_settle,
    OperationType.ASSET_PUBLISH_FEED_OPERATION to R.string.operation_description_asset_publish_feed,
    OperationType.WITNESS_CREATE_OPERATION to R.string.operation_description_witness_create,
    OperationType.WITNESS_UPDATE_OPERATION to R.string.operation_description_witness_update,
    OperationType.PROPOSAL_CREATE_OPERATION to R.string.operation_description_proposal_create,
    OperationType.PROPOSAL_UPDATE_OPERATION to R.string.operation_description_proposal_update,
    OperationType.PROPOSAL_DELETE_OPERATION to R.string.operation_description_proposal_delete,
    OperationType.WITHDRAW_PERMISSION_CREATE_OPERATION to R.string.operation_description_withdraw_permission_create,
    OperationType.WITHDRAW_PERMISSION_UPDATE_OPERATION to R.string.operation_description_withdraw_permission_update,
    OperationType.WITHDRAW_PERMISSION_CLAIM_OPERATION to R.string.operation_description_withdraw_permission_claim,
    OperationType.WITHDRAW_PERMISSION_DELETE_OPERATION to R.string.operation_description_withdraw_permission_delete,
    OperationType.COMMITTEE_MEMBER_CREATE_OPERATION to R.string.operation_description_committee_member_create,
    OperationType.COMMITTEE_MEMBER_UPDATE_OPERATION to R.string.operation_description_committee_member_update,
    OperationType.COMMITTEE_MEMBER_UPDATE_GLOBAL_PARAMETERS_OPERATION to R.string.operation_description_committee_member_update_global_parameters,
    OperationType.VESTING_BALANCE_CREATE_OPERATION to R.string.operation_description_vesting_balance_create,
    OperationType.VESTING_BALANCE_WITHDRAW_OPERATION to R.string.operation_description_vesting_balance_withdraw,
    OperationType.WORKER_CREATE_OPERATION to R.string.operation_description_worker_create,
    OperationType.CUSTOM_OPERATION to R.string.operation_description_custom,
    OperationType.ASSERT_OPERATION to R.string.operation_description_assert,
    OperationType.BALANCE_CLAIM_OPERATION to R.string.operation_description_balance_claim,
    OperationType.OVERRIDE_TRANSFER_OPERATION to R.string.operation_description_override_transfer,
    OperationType.TRANSFER_TO_BLIND_OPERATION to R.string.operation_description_transfer_to_blind,
    OperationType.BLIND_TRANSFER_OPERATION to R.string.operation_description_blind_transfer,
    OperationType.TRANSFER_FROM_BLIND_OPERATION to R.string.operation_description_transfer_from_blind,
    OperationType.ASSET_SETTLE_CANCEL_OPERATION to R.string.operation_description_asset_settle_cancel,
    OperationType.ASSET_CLAIM_FEES_OPERATION to R.string.operation_description_asset_claim_fees,
    OperationType.FBA_DISTRIBUTE_OPERATION to R.string.operation_description_fba_distribute,
    OperationType.BID_COLLATERAL_OPERATION to R.string.operation_description_bid_collateral,
    OperationType.EXECUTE_BID_OPERATION to R.string.operation_description_execute_bid,
    OperationType.ASSET_CLAIM_POOL_OPERATION to R.string.operation_description_asset_claim_pool,
    OperationType.ASSET_UPDATE_ISSUER_OPERATION to R.string.operation_description_asset_update_issuer,
    OperationType.HTLC_CREATE_OPERATION to R.string.operation_description_htlc_create,
    OperationType.HTLC_REDEEM_OPERATION to R.string.operation_description_htlc_redeem,
    OperationType.HTLC_REDEEMED_OPERATION to R.string.operation_description_htlc_redeemed,
    OperationType.HTLC_EXTEND_OPERATION to R.string.operation_description_htlc_extend,
    OperationType.HTLC_REFUND_OPERATION to R.string.operation_description_htlc_refund,
).withDefault { R.string.operation_description_unknown }
val operationColorResMap: Map<OperationType, Int> = mapOf(
    OperationType.TRANSFER_OPERATION to R.color.operation_transfer,
    OperationType.LIMIT_ORDER_CREATE_OPERATION to R.color.operation_limit_order_create,
    OperationType.LIMIT_ORDER_CANCEL_OPERATION to R.color.operation_limit_order_cancel,
    OperationType.CALL_ORDER_UPDATE_OPERATION to R.color.operation_call_order_update,
    OperationType.FILL_ORDER_OPERATION to R.color.operation_fill_order,
    OperationType.ACCOUNT_CREATE_OPERATION to R.color.operation_account_create,
    OperationType.ACCOUNT_UPDATE_OPERATION to R.color.operation_account_update,
    OperationType.ACCOUNT_WHITELIST_OPERATION to R.color.operation_account_whitelist,
    OperationType.ACCOUNT_UPGRADE_OPERATION to R.color.operation_account_upgrade,
    OperationType.ACCOUNT_TRANSFER_OPERATION to R.color.operation_account_transfer,
    OperationType.ASSET_CREATE_OPERATION to R.color.operation_asset_create,
    OperationType.ASSET_UPDATE_OPERATION to R.color.operation_asset_update,
    OperationType.ASSET_UPDATE_BITASSET_OPERATION to R.color.operation_asset_update_bitasset,
    OperationType.ASSET_UPDATE_FEED_PRODUCERS_OPERATION to R.color.operation_asset_update_feed_producers,
    OperationType.ASSET_ISSUE_OPERATION to R.color.operation_asset_issue,
    OperationType.ASSET_RESERVE_OPERATION to R.color.operation_asset_reserve,
    OperationType.ASSET_FUND_FEE_POOL_OPERATION to R.color.operation_asset_fund_fee_pool,
    OperationType.ASSET_SETTLE_OPERATION to R.color.operation_asset_settle,
    OperationType.ASSET_GLOBAL_SETTLE_OPERATION to R.color.operation_asset_global_settle,
    OperationType.ASSET_PUBLISH_FEED_OPERATION to R.color.operation_asset_publish_feed,
    OperationType.WITNESS_CREATE_OPERATION to R.color.operation_witness_create,
    OperationType.WITNESS_UPDATE_OPERATION to R.color.operation_witness_update,
    OperationType.PROPOSAL_CREATE_OPERATION to R.color.operation_proposal_create,
    OperationType.PROPOSAL_UPDATE_OPERATION to R.color.operation_proposal_update,
    OperationType.PROPOSAL_DELETE_OPERATION to R.color.operation_proposal_delete,
    OperationType.WITHDRAW_PERMISSION_CREATE_OPERATION to R.color.operation_withdraw_permission_create,
    OperationType.WITHDRAW_PERMISSION_UPDATE_OPERATION to R.color.operation_withdraw_permission_update,
    OperationType.WITHDRAW_PERMISSION_CLAIM_OPERATION to R.color.operation_withdraw_permission_claim,
    OperationType.WITHDRAW_PERMISSION_DELETE_OPERATION to R.color.operation_withdraw_permission_delete,
    OperationType.COMMITTEE_MEMBER_CREATE_OPERATION to R.color.operation_committee_member_create,
    OperationType.COMMITTEE_MEMBER_UPDATE_OPERATION to R.color.operation_committee_member_update,
    OperationType.COMMITTEE_MEMBER_UPDATE_GLOBAL_PARAMETERS_OPERATION to R.color.operation_committee_member_update_global_parameters,
    OperationType.VESTING_BALANCE_CREATE_OPERATION to R.color.operation_vesting_balance_create,
    OperationType.VESTING_BALANCE_WITHDRAW_OPERATION to R.color.operation_vesting_balance_withdraw,
    OperationType.WORKER_CREATE_OPERATION to R.color.operation_worker_create,
    OperationType.CUSTOM_OPERATION to R.color.operation_custom,
    OperationType.ASSERT_OPERATION to R.color.operation_assert,
    OperationType.BALANCE_CLAIM_OPERATION to R.color.operation_balance_claim,
    OperationType.OVERRIDE_TRANSFER_OPERATION to R.color.operation_override_transfer,
    OperationType.TRANSFER_TO_BLIND_OPERATION to R.color.operation_transfer_to_blind,
    OperationType.BLIND_TRANSFER_OPERATION to R.color.operation_blind_transfer,
    OperationType.TRANSFER_FROM_BLIND_OPERATION to R.color.operation_transfer_from_blind,
    OperationType.ASSET_SETTLE_CANCEL_OPERATION to R.color.operation_asset_settle_cancel,
    OperationType.ASSET_CLAIM_FEES_OPERATION to R.color.operation_asset_claim_fees,
    OperationType.FBA_DISTRIBUTE_OPERATION to R.color.operation_fba_distribute,
    OperationType.BID_COLLATERAL_OPERATION to R.color.operation_bid_collateral,
    OperationType.EXECUTE_BID_OPERATION to R.color.operation_execute_bid,
    OperationType.ASSET_CLAIM_POOL_OPERATION to R.color.operation_asset_claim_pool,
    OperationType.ASSET_UPDATE_ISSUER_OPERATION to R.color.operation_asset_update_issuer,
    OperationType.HTLC_CREATE_OPERATION to R.color.operation_htlc_create,
    OperationType.HTLC_REDEEM_OPERATION to R.color.operation_htlc_redeem,
    OperationType.HTLC_REDEEMED_OPERATION to R.color.operation_htlc_redeemed,
    OperationType.HTLC_EXTEND_OPERATION to R.color.operation_htlc_extend,
    OperationType.HTLC_REFUND_OPERATION to R.color.operation_htlc_refund,
).withDefault { R.color.operation_call_undefined }


val chainNameResMap: Map<ChainType, Int> = mapOf(
    ChainType.MAIN to R.string.chain_type_main,
    ChainType.TEST to R.string.chain_type_test,
    ChainType.UNKNOWN to R.string.chain_type_unknown
)
val chainColorResMap: Map<ChainType, Int> = mapOf(
    ChainType.MAIN to R.color.component_light,
    ChainType.TEST to R.color.component_warning,
    ChainType.UNKNOWN to R.color.component_dark_gray
)




